name: forecasting
channels:
  - conda-forge
dependencies:
  - python=3.12
  - geopandas
  - ipykernel
  - numpy
  - pandas
  - psycopg2
  - pydantic
  - python-dotenv
  - requests
  - sklearn
  - sqlalchemy